### ISSUE TITLE
Pod doesn’t work with use_frameworks

### ISSUE THREAD

**Issue by friedbunny** [friedbunny/NSTimeZone-Coordinate#1]
Because this is a category, we can’t easily use `+[NSBundle bundleForClass:]` to fetch the timezones plist. This means that when the pist does not exist in `mainBundle` (such as when CocoaPods is forcefully glueing everything together with `use_frameworks`) we can’t get the correct path and we fail to get a coordinate.

This means that integration via CocoaPods into a Swift project is broken.

**Comment by 1ec5** [comment]
The solution would be to add an internal “canary” class to use with `+[NSBundle bundleForClass:]`.
